# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
highlighter: rouge
encoding: utf-8
# Site settings
title: Comet
email: mosesag0813@comet.com
description: > Comet lets you build online.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://comet.io" # the base hostname & protocol for your site
github_username:  mosesag0813

# Build settings
markdown: kramdown
